version: "3"
services:
  web:
    image: "${DOCKER_IMAGE}"
    ports:
      - 8001:80
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
volumes:
  db_data: {}
